### ISSUE TITLE
v1.10.1 outdated doc  ?

### ISSUE THREAD

**Issue by EricDeveaud** [genome/joinx#9]
while reading the doc, it appears that we can use some -Dflag.

bic-soft:joinx-1.10.1/build > cmake28 -DBoost_USE_STATIC_LIBS=on -DBoost_NO_SYSTEM_PATHS=on ../
ends with
CMake Warning:
  Manually-specified variables were not used by the project:

    Boost_NO_SYSTEM_PATHS
    Boost_USE_STATIC_LIBS

-DBOOST_ROOT seems to be ignored, it always ends up building the vendor provided boost.

regards

Eric

**Comment by tabbott** [comment]
Fixed
